import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ThemeModeScript } from "flowbite-react";

import "./globals.css";

import { HeaderSection } from "./_components/layout/HeaderSection";
import { FooterSection } from "./_components/layout/FooterSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className + "relative"}>
        <HeaderSection />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
